version: "3"

services:
  laravel:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: "laravel"
      POSTGRES_PASSWORD: "laravel"
      POSTGRES_DB: "laravel"

    volumes:
      - ./db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"


